# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-mwaa
  description: Terraform module to provision Amazon Managed Workflows for Apache Airflow (MWAA)
  homepage: https://cloudposse.com/accelerate
  topics: ""


